### ISSUE TITLE
review krustlet-docs

### ISSUE THREAD

**Issue by flynnduism** [krustlet/krustlet-docs#1]
The site setup here is ready for some 👀 . I created a generic _Deis Labs_ docs theme as a starting point for our projects to use, and then branched off a _Krustlety_ version.

Both of these are based off of the [Docsy](https://github.com/google/docsy/) Hugo theme, which is ideal for Docs sites, has configuration for versioning, localization etc build in, and is [well documented](https://www.docsy.dev/docs/) itself. I've customized a few aspects, mostly the visuals and simplified the layout to two columns (instead of three).

# Krustlet Theme 

https://krustlet-docs.netlify.app/

# Deis Labs Theme

https://deislabs-theme--krustlet-docs.netlify.app/

**Comment by flynnduism** [comment]
The current plan is to publish this to docs.deislabs.io/krustlet
DNS stuff is all setup, though I have a cors/redirect issue to resolve before this is ready to :shipit:

**Comment by thomastaylor312** [comment]
This is now resolved and pointing to docs.krustlet.dev
