### ISSUE TITLE
Update path to bootstrapping script

### ISSUE THREAD

**Issue by kate-goldenring** [krustlet/krustlet-docs#15]
The [Bootstrapping Krustlet documentation](https://docs.krustlet.dev/howto/bootstrapping/) still points to the old script location within the docs folder (`./docs/howto/assets/bootstrap.sh`). Should be updated to point to (`scripts/bootstrap.sh`).

**Comment by bacongobbler** [comment]
Good catch.

Here's the document that needs updating: https://github.com/krustlet/krustlet-docs/blob/main/content/howto/bootstrapping.md
