### ISSUE TITLE
change baseURL to /

### ISSUE THREAD

**Issue by bacongobbler** [krustlet/krustlet-docs#4]
With the switch to https://docs.krustlet.dev/, we should probably switch the base URL to the root path (`/`) instead of `/krustlet`. The latter seems redundant in the context of https://docs.krustlet.dev/krustlet

Note that this change has the potential to break https://docs.deislabs.io/krustlet/, so any changes to this functionality should be handled with care.

https://github.com/deislabs/krustlet-docs/blob/3e2edcb956198a11f61f2a44f870966b639acd29/netlify.toml#L25-L29

**Comment by bacongobbler** [comment]
I also noticed that config.toml can be somewhat inconsistent at times... We should probably pick one domain and stick to it.

https://github.com/deislabs/krustlet-docs/blob/3e2edcb956198a11f61f2a44f870966b639acd29/config.toml#L1

https://github.com/deislabs/krustlet-docs/blob/3e2edcb956198a11f61f2a44f870966b639acd29/config.toml#L89

https://github.com/deislabs/krustlet-docs/blob/3e2edcb956198a11f61f2a44f870966b639acd29/config.toml#L51

https://github.com/deislabs/krustlet-docs/blob/3e2edcb956198a11f61f2a44f870966b639acd29/config.toml#L55

**Comment by thomastaylor312** [comment]
Completed in #10
